language: node_js

node_js:
  - "8"

sudo: required

deploy:
  provider: elasticbeanstalk
  access_key_id: $ACCESSKEYID
  secret_access_key:
    secure: "$SECRETACCESSKEY"
  region: "us-east-2c"
  app: "bb-server"
  env: "BB-Server-Env"
  bucket_name: "arn:aws:s3:::elasticbeanstalk-us-east-2-667050487006"
  on:
    branch: master

after_deploy:
  - echo "Done deploying"
